### ISSUE TITLE
Total Physical Memory

### ISSUE THREAD

**Issue by HonzaTNX** [EvotecIT/PowerBGInfo#1]
Hello.
I just found it, I like it, but it shows different memory size on my computer. PowerBGInfo shows 8GB, systeminfo shows 16GB and it should really be 16GB in the laptop. Am I doing something wrong?

Best regards

Honza

**Comment by PrzemyslawKlys** [comment]
Do you mean RAMSize shows 8GB? 

What does show?

```powershell
Get-CimInstance -ClassName Win32_PhysicalMemory -Property * | ft ConfiguredClockSpeed, PartNumber, Speed, Capacity
```
