### ISSUE TITLE
A parameter cannot be found that matches parameter name 'Extension'

### ISSUE THREAD

**Issue by MiDo1412** [EvotecIT/PowerBGInfo#14]
I get the following error on a Windows Server 2022:

```
Split-Path : A parameter cannot be found that matches parameter name 'Extension'.
At C:\Program Files\WindowsPowerShell\Modules\PowerBGInfo\0.0.4\PowerBGInfo.psm1:1019 char:49
+     $FileNameExtension = $FileName | Split-Path -Extension
+                                                 ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Split-Path], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.SplitPathCommand
```

This indicates the module. I'm a little lost. Is there a simple solution for this?

**Comment by PrzemyslawKlys** [comment]
Yes, it seems in PR
- https://github.com/EvotecIT/PowerBGInfo/pull/12

We didn't test for PowerShell 5.1, and only applied it to PS 7, which has the extension parameter. Lemme try to fix it.

**Comment by PrzemyslawKlys** [comment]
This is now fixed in version  0.0.5. Sorry for this.

**Comment by MiDo1412** [comment]
Wow, fast! Thanks!

**Comment by PrzemyslawKlys** [comment]
This change was proposed in:
- https://github.com/EvotecIT/PowerBGInfo/pull/12

I accepted this because I thought what was done before, was doing something wrong...  is it not working as expected.

**Comment by WoodyDev1** [comment]
So for future reference the output of the background will be appended with _PowerBgInfo? 
This is fine, just broke for us as we use registry to lockdown desktop background that looks at a specific path and file name.
Cheers for confirming.

**Comment by PrzemyslawKlys** [comment]
I think, for the future - you should never update modules globally without testing them first. Small changes like that and all things go to hell :/
