### ISSUE TITLE
Method Invocation Method: Addtext 

### ISSUE THREAD

**Issue by mkoenig10** [EvotecIT/PowerBGInfo#2]
Getting this error when I run the script..any ideas? 

Exception calling "AddText" with "6" argument(s): "Method not found: 'Void SixLabors.Fonts.TextOptions.set_Origin(System.Numerics.Vector2)'."
At C:\Program Files\WindowsPowerShell\Modules\PowerBGInfo\0.0.3\PowerBGInfo.psm1:717 char:13
+             $Image.AddText($PositionX + $HighestWidth + $SpaceBetween ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : MissingMethodException

**Comment by PrzemyslawKlys** [comment]
Did the modules load correctly? both PowerBGInfo or/and ImagePlayground?

**Comment by mkoenig10** [comment]
> 

I actually ended up using ISE instead of Visual Studio Code and it started working. Now just trying to figure out how to add MAC address, IP address and other items I like to use with BGINFO. Thanks!

**Comment by PrzemyslawKlys** [comment]
It's a problem with the VSCode PowerShell extension conflicting with some DLL in ImagePlayground; I still need to figure out which one and try to be able to fix it. Or use PS 7 to edit, and PS 5.1 to run it.

As for your stuff, take a look at PSSharedGoods and Get-COmputer* commands. It simplify things a lot.
