### ISSUE TITLE
Display Active IP Adresses

### ISSUE THREAD

**Issue by AnimatedAneurin** [EvotecIT/PowerBGInfo#6]
So I have yet to try out PowerBGInfo, but was curious to know if Displaying Active IP Addresses is already part of/or going to be part of PowerBGInfo.

Tried quickly looking through your documentation but could not find anything on it (May have missed it so I apologise if this is a waste of your time)

If not already implemented would it be possible to implement something like the below code?

```Get-WmiObject -Query "SELECT IPAddress FROM Win32_NetworkAdapterConfiguration WHERE IPEnabled = 'True'" | Select-Object -ExpandProperty IPAddress | Where-Object {$_ -like '*.*.*.*'}```

This is something we heavily used in BGInfo as End Users struggle to use CMD to provide IP Addresses to their IT Support. Only needed when users are remote workers using VPN and the DNS Server hasn't updated their records.

**Comment by AnimatedAneurin** [comment]
Just realised the asterisks is not showing in my original message. There's meant to be asterisks between the decimal points to represent the IP Address

**Comment by PrzemyslawKlys** [comment]
You know you can do that? You can create your own data with `New-BGInfoValue` right? As examples show there are some builtin values and those use BuiltinValue, but nothing stopos you from using New-BGInfoValue with Name and Value as shown below on Get-Disk command to deliver what you need - whatever it is.

```powershell
New-BGInfo -MonitorIndex 0 {
    # Lets add computer name, but lets use builtin values for that
    New-BGInfoValue -BuiltinValue HostName -Color Red -FontSize 20 -FontFamilyName 'Calibri'
    # Lets add user name, but lets use builtin values for that
    New-BGInfoValue -BuiltinValue FullUserName -Name "FullUserName" -Color White
    New-BGInfoValue -BuiltinValue CpuName
    New-BGInfoValue -BuiltinValue CpuLogicalCores
    New-BGInfoValue -BuiltinValue RAMSize
    New-BGInfoValue -BuiltinValue RAMSpeed

    # Lets add Label, but without any values, kind of like section starting
    New-BGInfoLabel -Name "Drives" -Color LemonChiffon -FontSize 16 -FontFamilyName 'Calibri'

    # Lets get all drives and their labels
    foreach ($Disk in (Get-Disk)) {
        $Volumes = $Disk | Get-Partition | Get-Volume
        foreach ($V in $Volumes) {
            New-BGInfoValue -Name "Drive $($V.DriveLetter)" -Value $V.SizeRemaining
        }
    }
} -FilePath $PSScriptRoot\Samples\PrzemyslawKlysAndKulkozaurr.jpg -ConfigurationDirectory $PSScriptRoot\Output -PositionX 100 -PositionY 100 -WallpaperFit Center
```

**Comment by AnimatedAneurin** [comment]
Ah that's great to hear. I spotted your script late last night so I only had a quick read through but, I'll have to give this a go. Thanks for the quick response.
