### ISSUE TITLE
SetWallpaper Error

### ISSUE THREAD

**Issue by AnimatedAneurin** [EvotecIT/PowerBGInfo#8]
I've managed to get to grips with your script since we last spoke and I've customised it to how we need it, except for an error that keeps appearing which I'm not entirely sure what's causing it

```Exception calling "SetWallpaper" with "2" argument(s): "Value does not fall within the expected range."...```

This error points to the DesktopManager Module and it directs me to line 29 character 52.

I imagine it's not anything to do with this but rather than the calling script of which I've created.

I've used your example as the base script and not changed anything to do with the functions parameters other than the image it uses and the positions of where the text gets placed.

Would you be able to help me find out the solution to this problem I'm having?

Thanks :)

**Comment by PrzemyslawKlys** [comment]
Without you providing some specifics what code you have that generrate this error it will be super hard to help you.

**Comment by AnimatedAneurin** [comment]
`Import-Module -Name "C:\Program Files\WindowsPowerShell\Modules\desktopmanager"
Import-Module -Name "C:\Program Files\WindowsPowerShell\Modules\imageplayground"
Import-Module -Name "C:\Program Files\WindowsPowerShell\Modules\powerbginfo"

if (!(Test-Path "C:\OutPut")) {
    New-Item -Path "c:\" -Name "Output" -ItemType "directory"
}

# Get all connected screens
$screens = [System.Windows.Forms.Screen]::AllScreens

foreach ($screen in $screens) {
    # Get the screen resolution
    $screenWidth = $screen.Bounds.Width
    $screenHeight = $screen.Bounds.Height
    Write-Host "Resolution: ", $screenWidth, "x" $screenHeight
    
    # Define percentages for x and y positions
    $positionXPercentage = 1.3  # Adjust this value as needed
    $positionYPercentage = 0.0075  # Adjust this value as needed
    
    # Calculate x and y positions
    $positionx = [math]::floor($screenWidth * $positionxPercentage)
    $positiony = [math]::floor($screenHeight * $positionyPercentage)
    Write-Host "Coordinates: ", $positionx, "x" $positiony
    
    # Output the results for each screen
    #Write-Host "Screen $($screen.DeviceName)"
    #Write-Host "Screen Width: $screenWidth"
    #Write-Host "Screen Height: $screenHeight"
    #Write-Host "X Position: $xPosition"
    #Write-Host "Y Position: $yPosition"
    #Write-Host ""
    #>
}

New-BGInfo -MonitorIndex 0 {
    # Lets add computer name, but lets use builtin values for that
    New-BGInfoValue -BuiltinValue HostName -Color Red -FontSize 20 -FontFamilyName 'Arial'
    New-BGInfoValue -BuiltinValue FullUserName -Name "FullUserName" -Color White -FontSize 16 -FontFamilyName 'Arial'
    New-BGInfoValue -BuiltinValue CpuName -Color White -FontSize 16 -FontFamilyName 'Arial'
    #New-BGInfoValue -BuiltinValue CpuLogicalCores -Color White -FontSize 16 -FontFamilyName 'Arial'
    #New-BGInfoValue -BuiltinValue RAMSize -Color White -FontSize 16 -FontFamilyName 'Arial'
    #New-BGInfoValue -BuiltinValue RAMSpeed -Color White -FontSize 16 -FontFamilyName 'Arial'

    # Lets add Label, but without any values, kind of like section starting
    #New-BGInfoLabel -Name "Drives5" -Color LemonChiffon -FontSize 16 -FontFamilyName 'Calibri'

    # Lets get all drives and their labels
    foreach ($Disk in (get-psdrive)) {
        $Volumes = $Disk | Where-Object { $_.Root -like "*:\*" } | Select-Object Root, @{Name='FreeSpaceInGB';Expression={[int]($_.Free / 1GB)}}
        foreach ($V in $Volumes) {
            New-BGInfoValue -Name "$($V.Root) Drive" -Value "$($V.FreeSpaceInGB)GB" -color White -FontSize 16 -FontFamilyName 'Arial'
        }
    }

    #$Drives = Get-PSDrive | Where-Object { $_.Root -like "*:\*" } | Select-Object Root, @{Name='FreeSpaceInGB';Expression={[int]($_.Free / 1GB)}} -expandproperty FreeSpaceInGB | Group-Object -Property FreeSpaceInGB

    #New-BGInfoValue -Name "Drives" -Value $Drives -color Red -FontSize 16 -FontFamilyName 'Calibri'

    $Test = Get-WmiObject -Query "SELECT IPAddress FROM Win32_NetworkAdapterConfiguration WHERE IPEnabled = 'True'" | Select-Object -ExpandProperty IPAddress | Where-Object {$_ -like '*.*.*.*'}

    New-BGInfoValue -Name "IP Addresses" -Value $Test -color White -FontSize 16 -FontFamilyName 'Arial'


} -FilePath C:\Windows\Web\Wallpaper\Windows\img19.jpg -ConfigurationDirectory $PSScriptRoot\Output -positionX $positionx -positionY $positiony -WallpaperFit Stretch`

**Comment by AnimatedAneurin** [comment]
Is this of any use? :)

**Comment by PrzemyslawKlys** [comment]
And id you just insert position X 10 and Position Y 10 does it still throw an error?

**Comment by PrzemyslawKlys** [comment]
So looking at this code of yours that you try to utilize:

![image](https://github.com/EvotecIT/PowerBGInfo/assets/15063294/c240030a-fd17-4de0-af4a-4648d4e5a4ac)

![image](https://github.com/EvotecIT/PowerBGInfo/assets/15063294/3956e749-1a7b-430c-acac-8ef77a48511b)

I would guess since you are using almost the very bottom left to add values, it tries to add them, but then goes out of bounds as the starting point for first line is X + number of pixels per line.

**Comment by PrzemyslawKlys** [comment]
Also I don't believe it's great idea to use WinForms. The Desktop manager you already have can show you things. 

![image](https://github.com/EvotecIT/PowerBGInfo/assets/15063294/dcd46f30-8ae3-4c54-925f-50bd92e981ec)


![image](https://github.com/EvotecIT/PowerBGInfo/assets/15063294/b4c4dd4a-8349-4931-ab9c-27eb4c8b6890)

**Comment by AnimatedAneurin** [comment]
So the coordinates are a weird one. You say that it shouldn't work, which I agree with you but I find that when I keep the numbers as I've posted them the information does go in the top right which is where I want them to be.

If I were to reduce those numbers they are no longer positioned correctly.

**Comment by AnimatedAneurin** [comment]
I was not aware that DesktopManager could provide that information so I'll check that out tomorrow

**Comment by AnimatedAneurin** [comment]
Also, keeping the positionx and positiony at the default numbers (default being 10) I still get the error

**Comment by PrzemyslawKlys** [comment]
"So the coordinates are a weird one. You say that it shouldn't work, which I agree with you but I find that when I keep the numbers as I've posted them the information does go in the top right which is where I want them to be."

"Also, keeping the positionx and positiony at the default numbers (default being 10) I still get the error"

So I am a bit lost - what is working and what is not working?

**Comment by AnimatedAneurin** [comment]
So the bit that isn't working is the error that I get that I mentioned in the first message I sent you.

I think it prevents setting the wallpaper automatically. I have to go into file explorer and set the desktop wallpaper manually

**Comment by AnimatedAneurin** [comment]
I managed to fix the issue. '$PSScriptRoot\Output' - this was preventing the script from working. So not an actual issue really as it was not my working directory
