### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by matthewandichabod** [EvotecIT/PowerBGInfo#9]
C:\ServerWallpaper\SystemBoot.ps1
﻿Import-Module : The term '﻿Import-Module' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At C:\ServerWallpaper\SystemBoot.ps1:1 char:1
+ ﻿Import-Module .\PowerBGInfo.psd1 -Force
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (﻿Import-Module:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
cmdlet New-BGInfo at command pipeline position 1
Supply values for the following parameters:
ConfigurationDirectory: 

I downloaded the script from GitHub and have had no luck running on my local pc

**Comment by PrzemyslawKlys** [comment]
Install-Module PowerBGInfo before doing Import-Module.

**Comment by matthewandichabod** [comment]
Thanks for that quick responce, I am still get this error

cmdlet New-BGInfo at command pipeline position 1
Supply values for the following parameters:
ConfigurationDirectory:

Is there a way to move the text to a different side of the screen

**Comment by PrzemyslawKlys** [comment]
You need to give it parameters it requires. Configuration directory is where the image will be saved.

**Comment by matthewandichabod** [comment]
is there a way to automate the configuration directory, so there is no need to type it every time?

**Comment by PrzemyslawKlys** [comment]
It's powershell so you provide parameters 

```powershell
New-BGInfo -MonitorIndex 0 {
    # Lets add computer name, but lets use builtin values for that
    New-BGInfoValue -BuiltinValue HostName -Color Red -FontSize 20 -FontFamilyName 'Calibri'
    # Lets add user name, but lets use builtin values for that
    New-BGInfoValue -BuiltinValue FullUserName -Name "User Name X" -Color White
    New-BGInfoValue -BuiltinValue CpuName
    New-BGInfoValue -BuiltinValue CpuLogicalCores
    New-BGInfoValue -BuiltinValue RAMSize
    New-BGInfoValue -BuiltinValue RAMSpeed

    # Lets add Label, but without any values, kind of like section starting
    New-BGInfoLabel -Name "Drives" -Color LemonChiffon -FontSize 16 -FontFamilyName 'Calibri'

    # Lets get all drives and their labels
    foreach ($Disk in (Get-Disk)) {
        $Volumes = $Disk | Get-Partition | Get-Volume
        foreach ($V in $Volumes) {
            New-BGInfoValue -Name "Drive $($V.DriveLetter)" -Value $V.SizeRemaining
        }
    }
} -FilePath $PSScriptRoot\Samples\PrzemyslawKlysAndKulkozaurr.jpg -ConfigurationDirectory $PSScriptRoot\Output -PositionX 100 -PositionY 100 -WallpaperFit Center
```

As you can see the configurationdirectory is given in examples, but if you run $PSScriptRoot in console, it doesn't work. You have full option to manage paths as you want.

**Comment by matthewandichabod** [comment]
Sorry to be a pain, i'm getting this error :( PS C:\Wallpaper> C:\Wallpaper\SystemBoot.ps1
Import-Module : The module to process 'PowerBGInfo.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Wallpaper\PowerBGInfo.psd1' was not processed because no valid module was found in any module 
directory.
At C:\Wallpaper\SystemBoot.ps1:2 char:1
+ Import-Module .\PowerBGInfo.psd1 -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (PowerBGInfo:String) [Import-Module], PSInvalidOperationException
    + FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by PrzemyslawKlys** [comment]
Import-Module PowerBGInfo 

If you installed module rather than using sources there's no need for .\XXX.psd1
